# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  pull_request:
    types: [opened,reopened,synchronize]
  push:
    branches: [master,release/**]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Extract version
      run: |
        if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
          echo "PACKAGE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        else
          git fetch --tags
          echo "PACKAGE_VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV
        fi
      
    - name: Build and generate NuGet package
      run: dotnet build jonteohr.bugsharp.csproj --configuration Release /p:GeneratePackageOnBuild=true /p:Version=${{ env.PACKAGE_VERSION }}
      working-directory: Jonteohr.BugSharp

    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
      working-directory: Jonteohr.BugSharp.Test
