name: NuGet

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      
      - name: Restore dependencies
        run: dotnet restore

      - name: Extract version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "PACKAGE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            git fetch --tags
            echo "PACKAGE_VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV
          fi

      - name: Build and generate NuGet package
        run: dotnet build Jonteohr.BugSharp/bugsharp.csproj --configuration Release /p:GeneratePackageOnBuild=true /p:Version=${{ env.PACKAGE_VERSION }}
        
      - name: Test
        run: dotnet test --no-build --verbosity normal
        
      - name: Push to NuGet
        run: dotnet nuget push ./bin/Release/*.nupkg --api-key ${{ secrets.NUGET_API }} --source https://api.nuget.org/v3/index.json